GAS_API: "https://data-api.defipulse.com/api/v1/egs/api/ethgasAPI.json?api-key=737dde1dd28ec1bf6e8e9fbb42ce0753da3f0bdd246c02b60af47d8d13e8",
EMAIL: 'wjasonmulings@gmail.com',
EMAIL_PASSWORD: 'NYCgoogle3'